### PR TITLE
add builder widgets for additional documentation

### PR DESCRIPTION
**Pull request by ca136**
Tabs and accordion:
image

### CODE REVIEW

**Comment by steve8708** [comment]
for best perf lets load them async like in this file https://github.com/BuilderIO/site/blob/main/src/components/widgets.tsx#L3

**Comment by ca136** [comment]
Do you get type warnings for these?
image

**Comment by ca136** [comment]
still works with the warnings:
image

**Comment by steve8708** [comment]
https://github.com/BuilderIO/site/blob/main/next-env.d.ts#L6:L6

**Review by steve8708 — APPROVED** [review]

**Pull request merged**
